language: erlang
notifications:
  recipients:
    - klaus.alfert@googlemail.com
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v0.13.3
  - make 
  - cd ..
before_script: 
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test"
